### ISSUE TITLE
Rewrite nose-style parametrization in test_quadrature to pytest

### ISSUE THREAD

**Issue by chrisrichardson** [FEniCS/fiat#24]
**[Original report](https://bitbucket.org/fenics-project/FIAT/issue/24) by Jan Blechta (Bitbucket: [blechta](https://bitbucket.org/blechta), GitHub: [blechta](https://github.com/blechta)).**

----------------------------------------

`test_quadrature` in the regression test uses `yield` to generate subtests. It works satisfactorily but it is not a standard pytest way.

**Comment by wence-** [comment]
Fixed in #31
